### ISSUE TITLE
Not closed quotation mark resulting in issue with email href link

### ISSUE THREAD

**Issue by intrepidbird** [Cellius-1/thernel#3]
The code you have written on your [contact.html](https://github.com/Cellius-1/thernel/blob/main/contact.html) page is as follows

```html
<div class="content" id="contact">
    <h2>Information</h2>
    <p>
    You can find my projects on 
    <a href="https://github.com/Cellius-1>GitHub</a>.
</p>
<p>
    You can also reach me via
    <a href="mailto:tharun.nagul@gmail.com">email.</a>.
</p>

</div>
```

As you can see, on line 31 (line 5 in the snippet), ` <a href="https://github.com/Cellius-1>GitHub</a>.` contains a unclosed link.

This causes the issue later with the link on the website, as shown below

![image](https://github.com/Cellius-1/thernel/assets/140008493/e3bd7351-ab14-4ec3-961d-253e60888b05)

The fixed code is 

```html
<div class="content" id="contact">
    <h2>Information</h2>
    <p>
    You can find my projects on 
    <a href="https://github.com/Cellius-1">GitHub</a>.
</p>
<p>
    You can also reach me via
    <a href="mailto:tharun.nagul@gmail.com">email.</a>.
</p>

</div>
```

The issue is very minor, but leads to a fairly major issue.

**Comment by Cellius-1** [comment]
Thanks! Implementing this now.
